// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pggwzviqnaketqgosuhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnZ3d6dmlxbmFrZXRxZ29zdWh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNDIyMDksImV4cCI6MjA2NzYxODIwOX0.JwUDckZ0qm0lPL2BB_QsGWO0R57H1oB-jM_7YHVMTSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});